services:
  # Backend API Service
  - type: web
    name: crypto-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter # Free tier
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
    # Add your secret environment variables in Render dashboard
    
  # Frontend Static Site
  - type: web
    name: crypto-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: starter # Free tier
    envVars:
      - key: PORT
        value: 80