services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/dist:/usr/share/nginx/html:ro
      - /dev/null:/etc/nginx/conf.d/default.conf  # This removes the default config
    depends_on:
      - backend
    restart: unless-stopped