services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    restart: unless-stopped

  frontend:
    build: ../frontend
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped