name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend deps
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests (skip if none)
        run: |
          cd backend
          pytest --maxfail=1 --disable-warnings -q || echo "No tests to run"
          
  test-frontend:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend deps
        run: |
          cd frontend
          npm ci

      - name: Run frontend tests (skip if none)
        run: |
          cd frontend
          npm test -- --watchAll=false || echo "No tests to run"
